name: Continuous Deployment
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure Git Credential Helper
        run: git config --global credential.helper store
        # Ensure token is authenticated properly
      - name: Login to Hugging Face
        run: huggingface-cli login --token ${{ secrets.HF }}
        # Set HF token as environment variable for make command
      - name: Set Hugging Face token as environment variable
        run: echo "HF=${{ secrets.HF }}" >> $GITHUB_ENV
      - name: Deployment To Hugging Face
        run: make deploy